#############################################################################
# Makefile for building: OthelloUI.app/Contents/MacOS/OthelloUI
# Generated by qmake (3.1) (Qt 5.9.7)
# Project:  OthelloUI.pro
# Template: app
# Command: /anaconda3/bin/qmake -o Makefile OthelloUI.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/anaconda3/include/qt -I/anaconda3/include/qt/QtWidgets -I/anaconda3/include/qt/QtGui -I/anaconda3/include/qt/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/anaconda3/mkspecs/macx-clang
QMAKE         = /anaconda3/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /anaconda3/bin/qmake -install qinstall
QINSTALL_PROGRAM = /anaconda3/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = OthelloUI1.0.0
DISTDIR = /Users/jessicawu/Desktop/OthelloUI/.tmp/OthelloUI1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/anaconda3/lib
LIBS          = $(SUBLIBS) -L/anaconda3/lib -lQt5Widgets -framework DiskArbitration -framework IOKit -lQt5Gui -lQt5Core -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = clickableBt.cpp \
		gameplay.cpp \
		logic.cpp \
		main.cpp qrc_bgb.cpp \
		qrc_bgo.cpp \
		qrc_bgx.cpp \
		qrc_res.cpp \
		moc_clickableBt.cpp \
		moc_gameplay.cpp
OBJECTS       = clickableBt.o \
		gameplay.o \
		logic.o \
		main.o \
		qrc_bgb.o \
		qrc_bgo.o \
		qrc_bgx.o \
		qrc_res.o \
		moc_clickableBt.o \
		moc_gameplay.o
DIST          = /anaconda3/mkspecs/features/spec_pre.prf \
		/anaconda3/mkspecs/qdevice.pri \
		/anaconda3/mkspecs/features/device_config.prf \
		/anaconda3/mkspecs/common/unix.conf \
		/anaconda3/mkspecs/common/mac.conf \
		/anaconda3/mkspecs/common/macx.conf \
		/anaconda3/mkspecs/common/sanitize.conf \
		/anaconda3/mkspecs/common/gcc-base.conf \
		/anaconda3/mkspecs/common/gcc-base-mac.conf \
		/anaconda3/mkspecs/common/clang.conf \
		/anaconda3/mkspecs/common/clang-mac.conf \
		/anaconda3/mkspecs/qconfig.pri \
		/anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_charts.pri \
		/anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_core.pri \
		/anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_designer.pri \
		/anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_gui.pri \
		/anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_help.pri \
		/anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_location.pri \
		/anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_macextras.pri \
		/anaconda3/mkspecs/modules/qt_lib_macextras_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_network.pri \
		/anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qml.pri \
		/anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quick.pri \
		/anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_script.pri \
		/anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_sql.pri \
		/anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_svg.pri \
		/anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		/anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webview.pri \
		/anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_xml.pri \
		/anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/anaconda3/mkspecs/features/qt_functions.prf \
		/anaconda3/mkspecs/features/qt_config.prf \
		/anaconda3/mkspecs/macx-clang/qmake.conf \
		/anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/anaconda3/mkspecs/features/exclusive_builds.prf \
		/anaconda3/mkspecs/features/mac/sdk.prf \
		/anaconda3/mkspecs/features/toolchain.prf \
		/anaconda3/mkspecs/features/mac/toolchain.prf \
		/anaconda3/mkspecs/features/default_pre.prf \
		/anaconda3/mkspecs/features/mac/default_pre.prf \
		/anaconda3/mkspecs/features/resolve_config.prf \
		/anaconda3/mkspecs/features/default_post.prf \
		/anaconda3/mkspecs/features/mac/default_post.prf \
		/anaconda3/mkspecs/features/mac/objective_c.prf \
		/anaconda3/mkspecs/features/warn_on.prf \
		/anaconda3/mkspecs/features/qt.prf \
		/anaconda3/mkspecs/features/resources.prf \
		/anaconda3/mkspecs/features/moc.prf \
		/anaconda3/mkspecs/features/unix/opengl.prf \
		/anaconda3/mkspecs/features/uic.prf \
		/anaconda3/mkspecs/features/unix/thread.prf \
		/anaconda3/mkspecs/features/qmake_use.prf \
		/anaconda3/mkspecs/features/file_copies.prf \
		/anaconda3/mkspecs/features/mac/rez.prf \
		/anaconda3/mkspecs/features/mac/asset_catalogs.prf \
		/anaconda3/mkspecs/features/testcase_targets.prf \
		/anaconda3/mkspecs/features/exceptions.prf \
		/anaconda3/mkspecs/features/yacc.prf \
		/anaconda3/mkspecs/features/lex.prf \
		OthelloUI.pro clickableBt.h \
		gameplay.h \
		lib.h \
		logic.h clickableBt.cpp \
		gameplay.cpp \
		logic.cpp \
		main.cpp
QMAKE_TARGET  = OthelloUI
DESTDIR       = 
TARGET        = OthelloUI.app/Contents/MacOS/OthelloUI

####### Custom Variables
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET): ui_gameplay.h $(OBJECTS)  
	@test -d OthelloUI.app/Contents/MacOS/ || mkdir -p OthelloUI.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OthelloUI.pro /anaconda3/mkspecs/macx-clang/qmake.conf /anaconda3/mkspecs/features/spec_pre.prf \
		/anaconda3/mkspecs/qdevice.pri \
		/anaconda3/mkspecs/features/device_config.prf \
		/anaconda3/mkspecs/common/unix.conf \
		/anaconda3/mkspecs/common/mac.conf \
		/anaconda3/mkspecs/common/macx.conf \
		/anaconda3/mkspecs/common/sanitize.conf \
		/anaconda3/mkspecs/common/gcc-base.conf \
		/anaconda3/mkspecs/common/gcc-base-mac.conf \
		/anaconda3/mkspecs/common/clang.conf \
		/anaconda3/mkspecs/common/clang-mac.conf \
		/anaconda3/mkspecs/qconfig.pri \
		/anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_charts.pri \
		/anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_core.pri \
		/anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_designer.pri \
		/anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_gui.pri \
		/anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_help.pri \
		/anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_location.pri \
		/anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_macextras.pri \
		/anaconda3/mkspecs/modules/qt_lib_macextras_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_network.pri \
		/anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qml.pri \
		/anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quick.pri \
		/anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_script.pri \
		/anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_sql.pri \
		/anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_svg.pri \
		/anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		/anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_webview.pri \
		/anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_xml.pri \
		/anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/anaconda3/mkspecs/features/qt_functions.prf \
		/anaconda3/mkspecs/features/qt_config.prf \
		/anaconda3/mkspecs/macx-clang/qmake.conf \
		/anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/anaconda3/mkspecs/features/exclusive_builds.prf \
		/anaconda3/mkspecs/features/mac/sdk.prf \
		/anaconda3/mkspecs/features/toolchain.prf \
		/anaconda3/mkspecs/features/mac/toolchain.prf \
		/anaconda3/mkspecs/features/default_pre.prf \
		/anaconda3/mkspecs/features/mac/default_pre.prf \
		/anaconda3/mkspecs/features/resolve_config.prf \
		/anaconda3/mkspecs/features/default_post.prf \
		/anaconda3/mkspecs/features/mac/default_post.prf \
		/anaconda3/mkspecs/features/mac/objective_c.prf \
		/anaconda3/mkspecs/features/warn_on.prf \
		/anaconda3/mkspecs/features/qt.prf \
		/anaconda3/mkspecs/features/resources.prf \
		/anaconda3/mkspecs/features/moc.prf \
		/anaconda3/mkspecs/features/unix/opengl.prf \
		/anaconda3/mkspecs/features/uic.prf \
		/anaconda3/mkspecs/features/unix/thread.prf \
		/anaconda3/mkspecs/features/qmake_use.prf \
		/anaconda3/mkspecs/features/file_copies.prf \
		/anaconda3/mkspecs/features/mac/rez.prf \
		/anaconda3/mkspecs/features/mac/asset_catalogs.prf \
		/anaconda3/mkspecs/features/testcase_targets.prf \
		/anaconda3/mkspecs/features/exceptions.prf \
		/anaconda3/mkspecs/features/yacc.prf \
		/anaconda3/mkspecs/features/lex.prf \
		OthelloUI.pro \
		bgb.qrc \
		bgo.qrc \
		bgx.qrc \
		res.qrc \
		/anaconda3/lib/libQt5Widgets.prl \
		/anaconda3/lib/libQt5Gui.prl \
		/anaconda3/lib/libQt5Core.prl
	$(QMAKE) -o Makefile OthelloUI.pro
/anaconda3/mkspecs/features/spec_pre.prf:
/anaconda3/mkspecs/qdevice.pri:
/anaconda3/mkspecs/features/device_config.prf:
/anaconda3/mkspecs/common/unix.conf:
/anaconda3/mkspecs/common/mac.conf:
/anaconda3/mkspecs/common/macx.conf:
/anaconda3/mkspecs/common/sanitize.conf:
/anaconda3/mkspecs/common/gcc-base.conf:
/anaconda3/mkspecs/common/gcc-base-mac.conf:
/anaconda3/mkspecs/common/clang.conf:
/anaconda3/mkspecs/common/clang-mac.conf:
/anaconda3/mkspecs/qconfig.pri:
/anaconda3/mkspecs/modules/qt_lib_3danimation.pri:
/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dcore.pri:
/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dextras.pri:
/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dinput.pri:
/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri:
/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquick.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/anaconda3/mkspecs/modules/qt_lib_3drender.pri:
/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri:
/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri:
/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri:
/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri:
/anaconda3/mkspecs/modules/qt_lib_cgl_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_charts.pri:
/anaconda3/mkspecs/modules/qt_lib_charts_private.pri:
/anaconda3/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_concurrent.pri:
/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri:
/anaconda3/mkspecs/modules/qt_lib_core.pri:
/anaconda3/mkspecs/modules/qt_lib_core_private.pri:
/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri:
/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri:
/anaconda3/mkspecs/modules/qt_lib_dbus.pri:
/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri:
/anaconda3/mkspecs/modules/qt_lib_designer.pri:
/anaconda3/mkspecs/modules/qt_lib_designer_private.pri:
/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri:
/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_gamepad.pri:
/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri:
/anaconda3/mkspecs/modules/qt_lib_graphics_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_gui.pri:
/anaconda3/mkspecs/modules/qt_lib_gui_private.pri:
/anaconda3/mkspecs/modules/qt_lib_help.pri:
/anaconda3/mkspecs/modules/qt_lib_help_private.pri:
/anaconda3/mkspecs/modules/qt_lib_location.pri:
/anaconda3/mkspecs/modules/qt_lib_location_private.pri:
/anaconda3/mkspecs/modules/qt_lib_macextras.pri:
/anaconda3/mkspecs/modules/qt_lib_macextras_private.pri:
/anaconda3/mkspecs/modules/qt_lib_multimedia.pri:
/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri:
/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri:
/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/anaconda3/mkspecs/modules/qt_lib_network.pri:
/anaconda3/mkspecs/modules/qt_lib_network_private.pri:
/anaconda3/mkspecs/modules/qt_lib_networkauth.pri:
/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri:
/anaconda3/mkspecs/modules/qt_lib_nfc.pri:
/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri:
/anaconda3/mkspecs/modules/qt_lib_opengl.pri:
/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri:
/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri:
/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri:
/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_positioning.pri:
/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri:
/anaconda3/mkspecs/modules/qt_lib_printsupport.pri:
/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri:
/anaconda3/mkspecs/modules/qt_lib_purchasing.pri:
/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri:
/anaconda3/mkspecs/modules/qt_lib_qml.pri:
/anaconda3/mkspecs/modules/qt_lib_qml_private.pri:
/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri:
/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/anaconda3/mkspecs/modules/qt_lib_qmltest.pri:
/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri:
/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/anaconda3/mkspecs/modules/qt_lib_quick.pri:
/anaconda3/mkspecs/modules/qt_lib_quick_private.pri:
/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri:
/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri:
/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri:
/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri:
/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/anaconda3/mkspecs/modules/qt_lib_repparser.pri:
/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri:
/anaconda3/mkspecs/modules/qt_lib_script.pri:
/anaconda3/mkspecs/modules/qt_lib_script_private.pri:
/anaconda3/mkspecs/modules/qt_lib_scripttools.pri:
/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri:
/anaconda3/mkspecs/modules/qt_lib_scxml.pri:
/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri:
/anaconda3/mkspecs/modules/qt_lib_sensors.pri:
/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri:
/anaconda3/mkspecs/modules/qt_lib_serialbus.pri:
/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri:
/anaconda3/mkspecs/modules/qt_lib_serialport.pri:
/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri:
/anaconda3/mkspecs/modules/qt_lib_sql.pri:
/anaconda3/mkspecs/modules/qt_lib_sql_private.pri:
/anaconda3/mkspecs/modules/qt_lib_svg.pri:
/anaconda3/mkspecs/modules/qt_lib_svg_private.pri:
/anaconda3/mkspecs/modules/qt_lib_testlib.pri:
/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri:
/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri:
/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri:
/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri:
/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri:
/anaconda3/mkspecs/modules/qt_lib_uitools.pri:
/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri:
/anaconda3/mkspecs/modules/qt_lib_webchannel.pri:
/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri:
/anaconda3/mkspecs/modules/qt_lib_webengine.pri:
/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri:
/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri:
/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri:
/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri:
/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/anaconda3/mkspecs/modules/qt_lib_websockets.pri:
/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri:
/anaconda3/mkspecs/modules/qt_lib_webview.pri:
/anaconda3/mkspecs/modules/qt_lib_webview_private.pri:
/anaconda3/mkspecs/modules/qt_lib_widgets.pri:
/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri:
/anaconda3/mkspecs/modules/qt_lib_xml.pri:
/anaconda3/mkspecs/modules/qt_lib_xml_private.pri:
/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri:
/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/anaconda3/mkspecs/features/qt_functions.prf:
/anaconda3/mkspecs/features/qt_config.prf:
/anaconda3/mkspecs/macx-clang/qmake.conf:
/anaconda3/mkspecs/features/spec_post.prf:
.qmake.stash:
/anaconda3/mkspecs/features/exclusive_builds.prf:
/anaconda3/mkspecs/features/mac/sdk.prf:
/anaconda3/mkspecs/features/toolchain.prf:
/anaconda3/mkspecs/features/mac/toolchain.prf:
/anaconda3/mkspecs/features/default_pre.prf:
/anaconda3/mkspecs/features/mac/default_pre.prf:
/anaconda3/mkspecs/features/resolve_config.prf:
/anaconda3/mkspecs/features/default_post.prf:
/anaconda3/mkspecs/features/mac/default_post.prf:
/anaconda3/mkspecs/features/mac/objective_c.prf:
/anaconda3/mkspecs/features/warn_on.prf:
/anaconda3/mkspecs/features/qt.prf:
/anaconda3/mkspecs/features/resources.prf:
/anaconda3/mkspecs/features/moc.prf:
/anaconda3/mkspecs/features/unix/opengl.prf:
/anaconda3/mkspecs/features/uic.prf:
/anaconda3/mkspecs/features/unix/thread.prf:
/anaconda3/mkspecs/features/qmake_use.prf:
/anaconda3/mkspecs/features/file_copies.prf:
/anaconda3/mkspecs/features/mac/rez.prf:
/anaconda3/mkspecs/features/mac/asset_catalogs.prf:
/anaconda3/mkspecs/features/testcase_targets.prf:
/anaconda3/mkspecs/features/exceptions.prf:
/anaconda3/mkspecs/features/yacc.prf:
/anaconda3/mkspecs/features/lex.prf:
OthelloUI.pro:
bgb.qrc:
bgo.qrc:
bgx.qrc:
res.qrc:
/anaconda3/lib/libQt5Widgets.prl:
/anaconda3/lib/libQt5Gui.prl:
/anaconda3/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile OthelloUI.pro

qmake_all: FORCE

OthelloUI.app/Contents/PkgInfo: 
	@test -d OthelloUI.app/Contents || mkdir -p OthelloUI.app/Contents
	@$(DEL_FILE) OthelloUI.app/Contents/PkgInfo
	@echo "APPL????" > OthelloUI.app/Contents/PkgInfo
OthelloUI.app/Contents/Resources/empty.lproj: 
	@test -d OthelloUI.app/Contents/Resources || mkdir -p OthelloUI.app/Contents/Resources
	@touch OthelloUI.app/Contents/Resources/empty.lproj
	
OthelloUI.app/Contents/Info.plist: 
	@test -d OthelloUI.app/Contents || mkdir -p OthelloUI.app/Contents
	@$(DEL_FILE) OthelloUI.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.jessica.OthelloUI,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,OthelloUI,g" -e "s,@LIBRARY@,OthelloUI,g" -e "s,@TYPEINFO@,????,g" /anaconda3/mkspecs/macx-clang/Info.plist.app >OthelloUI.app/Contents/Info.plist

all: Makefile \
		OthelloUI.app/Contents/PkgInfo \
		OthelloUI.app/Contents/Resources/empty.lproj \
		OthelloUI.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents bgb.qrc bgo.qrc bgx.qrc res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /anaconda3/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents clickableBt.h gameplay.h lib.h logic.h $(DISTDIR)/
	$(COPY_FILE) --parents clickableBt.cpp gameplay.cpp logic.cpp main.cpp $(DISTDIR)/
	$(COPY_FILE) --parents gameplay.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r OthelloUI.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_bgb.cpp qrc_bgo.cpp qrc_bgx.cpp qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_bgb.cpp qrc_bgo.cpp qrc_bgx.cpp qrc_res.cpp
qrc_bgb.cpp: bgb.qrc \
		/anaconda3/bin/rcc \
		bgb.png
	/anaconda3/bin/rcc -name bgb bgb.qrc -o qrc_bgb.cpp

qrc_bgo.cpp: bgo.qrc \
		/anaconda3/bin/rcc \
		bgo.png
	/anaconda3/bin/rcc -name bgo bgo.qrc -o qrc_bgo.cpp

qrc_bgx.cpp: bgx.qrc \
		/anaconda3/bin/rcc \
		bgx.png
	/anaconda3/bin/rcc -name bgx bgx.qrc -o qrc_bgx.cpp

qrc_res.cpp: res.qrc \
		/anaconda3/bin/rcc \
		../bgo.png \
		bgb.png
	/anaconda3/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /anaconda3/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h /anaconda3/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_clickableBt.cpp moc_gameplay.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_clickableBt.cpp moc_gameplay.cpp
moc_clickableBt.cpp: /anaconda3/include/qt/QtWidgets/QLabel \
		/anaconda3/include/qt/QtWidgets/qlabel.h \
		/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		/anaconda3/include/qt/QtGui/qtguiglobal.h \
		/anaconda3/include/qt/QtCore/qglobal.h \
		/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/anaconda3/include/qt/QtCore/qconfig.h \
		/anaconda3/include/qt/QtCore/qtcore-config.h \
		/anaconda3/include/qt/QtCore/qsystemdetection.h \
		/anaconda3/include/qt/QtCore/qprocessordetection.h \
		/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/anaconda3/include/qt/QtCore/qtypeinfo.h \
		/anaconda3/include/qt/QtCore/qsysinfo.h \
		/anaconda3/include/qt/QtCore/qlogging.h \
		/anaconda3/include/qt/QtCore/qflags.h \
		/anaconda3/include/qt/QtCore/qatomic.h \
		/anaconda3/include/qt/QtCore/qbasicatomic.h \
		/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/anaconda3/include/qt/QtCore/qgenericatomic.h \
		/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/anaconda3/include/qt/QtCore/qglobalstatic.h \
		/anaconda3/include/qt/QtCore/qmutex.h \
		/anaconda3/include/qt/QtCore/qnumeric.h \
		/anaconda3/include/qt/QtCore/qversiontagging.h \
		/anaconda3/include/qt/QtGui/qtgui-config.h \
		/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		/anaconda3/include/qt/QtWidgets/qframe.h \
		/anaconda3/include/qt/QtWidgets/qwidget.h \
		/anaconda3/include/qt/QtGui/qwindowdefs.h \
		/anaconda3/include/qt/QtCore/qobjectdefs.h \
		/anaconda3/include/qt/QtCore/qnamespace.h \
		/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		/anaconda3/include/qt/QtCore/qobject.h \
		/anaconda3/include/qt/QtCore/qstring.h \
		/anaconda3/include/qt/QtCore/qchar.h \
		/anaconda3/include/qt/QtCore/qbytearray.h \
		/anaconda3/include/qt/QtCore/qrefcount.h \
		/anaconda3/include/qt/QtCore/qarraydata.h \
		/anaconda3/include/qt/QtCore/qstringbuilder.h \
		/anaconda3/include/qt/QtCore/qlist.h \
		/anaconda3/include/qt/QtCore/qalgorithms.h \
		/anaconda3/include/qt/QtCore/qiterator.h \
		/anaconda3/include/qt/QtCore/qhashfunctions.h \
		/anaconda3/include/qt/QtCore/qpair.h \
		/anaconda3/include/qt/QtCore/qbytearraylist.h \
		/anaconda3/include/qt/QtCore/qstringlist.h \
		/anaconda3/include/qt/QtCore/qregexp.h \
		/anaconda3/include/qt/QtCore/qstringmatcher.h \
		/anaconda3/include/qt/QtCore/qcoreevent.h \
		/anaconda3/include/qt/QtCore/qscopedpointer.h \
		/anaconda3/include/qt/QtCore/qmetatype.h \
		/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/anaconda3/include/qt/QtCore/qobject_impl.h \
		/anaconda3/include/qt/QtCore/qmargins.h \
		/anaconda3/include/qt/QtGui/qpaintdevice.h \
		/anaconda3/include/qt/QtCore/qrect.h \
		/anaconda3/include/qt/QtCore/qsize.h \
		/anaconda3/include/qt/QtCore/qpoint.h \
		/anaconda3/include/qt/QtGui/qpalette.h \
		/anaconda3/include/qt/QtGui/qcolor.h \
		/anaconda3/include/qt/QtGui/qrgb.h \
		/anaconda3/include/qt/QtGui/qrgba64.h \
		/anaconda3/include/qt/QtGui/qbrush.h \
		/anaconda3/include/qt/QtCore/qvector.h \
		/anaconda3/include/qt/QtGui/qmatrix.h \
		/anaconda3/include/qt/QtGui/qpolygon.h \
		/anaconda3/include/qt/QtGui/qregion.h \
		/anaconda3/include/qt/QtCore/qdatastream.h \
		/anaconda3/include/qt/QtCore/qiodevice.h \
		/anaconda3/include/qt/QtCore/qline.h \
		/anaconda3/include/qt/QtGui/qtransform.h \
		/anaconda3/include/qt/QtGui/qpainterpath.h \
		/anaconda3/include/qt/QtGui/qimage.h \
		/anaconda3/include/qt/QtGui/qpixelformat.h \
		/anaconda3/include/qt/QtGui/qpixmap.h \
		/anaconda3/include/qt/QtCore/qsharedpointer.h \
		/anaconda3/include/qt/QtCore/qshareddata.h \
		/anaconda3/include/qt/QtCore/qhash.h \
		/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		/anaconda3/include/qt/QtGui/qfont.h \
		/anaconda3/include/qt/QtGui/qfontmetrics.h \
		/anaconda3/include/qt/QtGui/qfontinfo.h \
		/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		/anaconda3/include/qt/QtGui/qcursor.h \
		/anaconda3/include/qt/QtGui/qkeysequence.h \
		/anaconda3/include/qt/QtGui/qevent.h \
		/anaconda3/include/qt/QtCore/qvariant.h \
		/anaconda3/include/qt/QtCore/qmap.h \
		/anaconda3/include/qt/QtCore/qdebug.h \
		/anaconda3/include/qt/QtCore/qtextstream.h \
		/anaconda3/include/qt/QtCore/qlocale.h \
		/anaconda3/include/qt/QtCore/qset.h \
		/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		/anaconda3/include/qt/QtCore/qurl.h \
		/anaconda3/include/qt/QtCore/qurlquery.h \
		/anaconda3/include/qt/QtCore/qfile.h \
		/anaconda3/include/qt/QtCore/qfiledevice.h \
		/anaconda3/include/qt/QtGui/qvector2d.h \
		/anaconda3/include/qt/QtGui/qtouchdevice.h \
		clickableBt.h \
		moc_predefs.h \
		/anaconda3/bin/moc
	/anaconda3/bin/moc $(DEFINES) --include ./moc_predefs.h -I/anaconda3/mkspecs/macx-clang -I/Users/jessicawu/Desktop/OthelloUI -I/Users/jessicawu/Desktop/OthelloUI -I/anaconda3/include/qt -I/anaconda3/include/qt/QtWidgets -I/anaconda3/include/qt/QtGui -I/anaconda3/include/qt/QtCore -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include clickableBt.h -o moc_clickableBt.cpp

moc_gameplay.cpp: /anaconda3/include/qt/QtWidgets/QMainWindow \
		/anaconda3/include/qt/QtWidgets/qmainwindow.h \
		/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		/anaconda3/include/qt/QtGui/qtguiglobal.h \
		/anaconda3/include/qt/QtCore/qglobal.h \
		/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/anaconda3/include/qt/QtCore/qconfig.h \
		/anaconda3/include/qt/QtCore/qtcore-config.h \
		/anaconda3/include/qt/QtCore/qsystemdetection.h \
		/anaconda3/include/qt/QtCore/qprocessordetection.h \
		/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/anaconda3/include/qt/QtCore/qtypeinfo.h \
		/anaconda3/include/qt/QtCore/qsysinfo.h \
		/anaconda3/include/qt/QtCore/qlogging.h \
		/anaconda3/include/qt/QtCore/qflags.h \
		/anaconda3/include/qt/QtCore/qatomic.h \
		/anaconda3/include/qt/QtCore/qbasicatomic.h \
		/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/anaconda3/include/qt/QtCore/qgenericatomic.h \
		/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/anaconda3/include/qt/QtCore/qglobalstatic.h \
		/anaconda3/include/qt/QtCore/qmutex.h \
		/anaconda3/include/qt/QtCore/qnumeric.h \
		/anaconda3/include/qt/QtCore/qversiontagging.h \
		/anaconda3/include/qt/QtGui/qtgui-config.h \
		/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		/anaconda3/include/qt/QtWidgets/qwidget.h \
		/anaconda3/include/qt/QtGui/qwindowdefs.h \
		/anaconda3/include/qt/QtCore/qobjectdefs.h \
		/anaconda3/include/qt/QtCore/qnamespace.h \
		/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		/anaconda3/include/qt/QtCore/qobject.h \
		/anaconda3/include/qt/QtCore/qstring.h \
		/anaconda3/include/qt/QtCore/qchar.h \
		/anaconda3/include/qt/QtCore/qbytearray.h \
		/anaconda3/include/qt/QtCore/qrefcount.h \
		/anaconda3/include/qt/QtCore/qarraydata.h \
		/anaconda3/include/qt/QtCore/qstringbuilder.h \
		/anaconda3/include/qt/QtCore/qlist.h \
		/anaconda3/include/qt/QtCore/qalgorithms.h \
		/anaconda3/include/qt/QtCore/qiterator.h \
		/anaconda3/include/qt/QtCore/qhashfunctions.h \
		/anaconda3/include/qt/QtCore/qpair.h \
		/anaconda3/include/qt/QtCore/qbytearraylist.h \
		/anaconda3/include/qt/QtCore/qstringlist.h \
		/anaconda3/include/qt/QtCore/qregexp.h \
		/anaconda3/include/qt/QtCore/qstringmatcher.h \
		/anaconda3/include/qt/QtCore/qcoreevent.h \
		/anaconda3/include/qt/QtCore/qscopedpointer.h \
		/anaconda3/include/qt/QtCore/qmetatype.h \
		/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/anaconda3/include/qt/QtCore/qobject_impl.h \
		/anaconda3/include/qt/QtCore/qmargins.h \
		/anaconda3/include/qt/QtGui/qpaintdevice.h \
		/anaconda3/include/qt/QtCore/qrect.h \
		/anaconda3/include/qt/QtCore/qsize.h \
		/anaconda3/include/qt/QtCore/qpoint.h \
		/anaconda3/include/qt/QtGui/qpalette.h \
		/anaconda3/include/qt/QtGui/qcolor.h \
		/anaconda3/include/qt/QtGui/qrgb.h \
		/anaconda3/include/qt/QtGui/qrgba64.h \
		/anaconda3/include/qt/QtGui/qbrush.h \
		/anaconda3/include/qt/QtCore/qvector.h \
		/anaconda3/include/qt/QtGui/qmatrix.h \
		/anaconda3/include/qt/QtGui/qpolygon.h \
		/anaconda3/include/qt/QtGui/qregion.h \
		/anaconda3/include/qt/QtCore/qdatastream.h \
		/anaconda3/include/qt/QtCore/qiodevice.h \
		/anaconda3/include/qt/QtCore/qline.h \
		/anaconda3/include/qt/QtGui/qtransform.h \
		/anaconda3/include/qt/QtGui/qpainterpath.h \
		/anaconda3/include/qt/QtGui/qimage.h \
		/anaconda3/include/qt/QtGui/qpixelformat.h \
		/anaconda3/include/qt/QtGui/qpixmap.h \
		/anaconda3/include/qt/QtCore/qsharedpointer.h \
		/anaconda3/include/qt/QtCore/qshareddata.h \
		/anaconda3/include/qt/QtCore/qhash.h \
		/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		/anaconda3/include/qt/QtGui/qfont.h \
		/anaconda3/include/qt/QtGui/qfontmetrics.h \
		/anaconda3/include/qt/QtGui/qfontinfo.h \
		/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		/anaconda3/include/qt/QtGui/qcursor.h \
		/anaconda3/include/qt/QtGui/qkeysequence.h \
		/anaconda3/include/qt/QtGui/qevent.h \
		/anaconda3/include/qt/QtCore/qvariant.h \
		/anaconda3/include/qt/QtCore/qmap.h \
		/anaconda3/include/qt/QtCore/qdebug.h \
		/anaconda3/include/qt/QtCore/qtextstream.h \
		/anaconda3/include/qt/QtCore/qlocale.h \
		/anaconda3/include/qt/QtCore/qset.h \
		/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		/anaconda3/include/qt/QtCore/qurl.h \
		/anaconda3/include/qt/QtCore/qurlquery.h \
		/anaconda3/include/qt/QtCore/qfile.h \
		/anaconda3/include/qt/QtCore/qfiledevice.h \
		/anaconda3/include/qt/QtGui/qvector2d.h \
		/anaconda3/include/qt/QtGui/qtouchdevice.h \
		/anaconda3/include/qt/QtWidgets/qtabwidget.h \
		/anaconda3/include/qt/QtGui/qicon.h \
		logic.h \
		/anaconda3/include/qt/QtGui/QPixmap \
		clickableBt.h \
		/anaconda3/include/qt/QtWidgets/QLabel \
		/anaconda3/include/qt/QtWidgets/qlabel.h \
		/anaconda3/include/qt/QtWidgets/qframe.h \
		ui_gameplay.h \
		/anaconda3/include/qt/QtCore/QtCore \
		/anaconda3/include/qt/QtCore/QtCoreDepends \
		/anaconda3/include/qt/QtCore/qabstractanimation.h \
		/anaconda3/include/qt/QtCore/qabstracteventdispatcher.h \
		/anaconda3/include/qt/QtCore/qeventloop.h \
		/anaconda3/include/qt/QtCore/qabstractitemmodel.h \
		/anaconda3/include/qt/QtCore/qabstractnativeeventfilter.h \
		/anaconda3/include/qt/QtCore/qabstractproxymodel.h \
		/anaconda3/include/qt/QtCore/qabstractstate.h \
		/anaconda3/include/qt/QtCore/qabstracttransition.h \
		/anaconda3/include/qt/QtCore/qanimationgroup.h \
		/anaconda3/include/qt/QtCore/qarraydataops.h \
		/anaconda3/include/qt/QtCore/qarraydatapointer.h \
		/anaconda3/include/qt/QtCore/qbasictimer.h \
		/anaconda3/include/qt/QtCore/qbitarray.h \
		/anaconda3/include/qt/QtCore/qbuffer.h \
		/anaconda3/include/qt/QtCore/qbytearraymatcher.h \
		/anaconda3/include/qt/QtCore/qcache.h \
		/anaconda3/include/qt/QtCore/qcollator.h \
		/anaconda3/include/qt/QtCore/qcommandlineoption.h \
		/anaconda3/include/qt/QtCore/qcommandlineparser.h \
		/anaconda3/include/qt/QtCore/qcoreapplication.h \
		/anaconda3/include/qt/QtCore/qcryptographichash.h \
		/anaconda3/include/qt/QtCore/qdatetime.h \
		/anaconda3/include/qt/QtCore/qdeadlinetimer.h \
		/anaconda3/include/qt/QtCore/qelapsedtimer.h \
		/anaconda3/include/qt/QtCore/qdir.h \
		/anaconda3/include/qt/QtCore/qfileinfo.h \
		/anaconda3/include/qt/QtCore/qdiriterator.h \
		/anaconda3/include/qt/QtCore/qeasingcurve.h \
		/anaconda3/include/qt/QtCore/qendian.h \
		/anaconda3/include/qt/QtCore/qeventtransition.h \
		/anaconda3/include/qt/QtCore/qexception.h \
		/anaconda3/include/qt/QtCore/qfactoryinterface.h \
		/anaconda3/include/qt/QtCore/qfileselector.h \
		/anaconda3/include/qt/QtCore/QObject \
		/anaconda3/include/qt/QtCore/QStringList \
		/anaconda3/include/qt/QtCore/qfilesystemwatcher.h \
		/anaconda3/include/qt/QtCore/qfinalstate.h \
		/anaconda3/include/qt/QtCore/qfuture.h \
		/anaconda3/include/qt/QtCore/qfutureinterface.h \
		/anaconda3/include/qt/QtCore/qrunnable.h \
		/anaconda3/include/qt/QtCore/qresultstore.h \
		/anaconda3/include/qt/QtCore/qfuturesynchronizer.h \
		/anaconda3/include/qt/QtCore/qfuturewatcher.h \
		/anaconda3/include/qt/QtCore/qhistorystate.h \
		/anaconda3/include/qt/QtCore/qidentityproxymodel.h \
		/anaconda3/include/qt/QtCore/qisenum.h \
		/anaconda3/include/qt/QtCore/qitemselectionmodel.h \
		/anaconda3/include/qt/QtCore/qjsonarray.h \
		/anaconda3/include/qt/QtCore/qjsonvalue.h \
		/anaconda3/include/qt/QtCore/qjsondocument.h \
		/anaconda3/include/qt/QtCore/qjsonobject.h \
		/anaconda3/include/qt/QtCore/qlibrary.h \
		/anaconda3/include/qt/QtCore/qlibraryinfo.h \
		/anaconda3/include/qt/QtCore/qversionnumber.h \
		/anaconda3/include/qt/QtCore/qlinkedlist.h \
		/anaconda3/include/qt/QtCore/qlockfile.h \
		/anaconda3/include/qt/QtCore/qloggingcategory.h \
		/anaconda3/include/qt/QtCore/qmath.h \
		/anaconda3/include/qt/QtCore/qmessageauthenticationcode.h \
		/anaconda3/include/qt/QtCore/qmetaobject.h \
		/anaconda3/include/qt/QtCore/qmimedata.h \
		/anaconda3/include/qt/QtCore/qmimedatabase.h \
		/anaconda3/include/qt/QtCore/qmimetype.h \
		/anaconda3/include/qt/QtCore/qobjectcleanuphandler.h \
		/anaconda3/include/qt/QtCore/qoperatingsystemversion.h \
		/anaconda3/include/qt/QtCore/qparallelanimationgroup.h \
		/anaconda3/include/qt/QtCore/qpauseanimation.h \
		/anaconda3/include/qt/QtCore/qplugin.h \
		/anaconda3/include/qt/QtCore/qpointer.h \
		/anaconda3/include/qt/QtCore/qpluginloader.h \
		/anaconda3/include/qt/QtCore/qprocess.h \
		/anaconda3/include/qt/QtCore/qpropertyanimation.h \
		/anaconda3/include/qt/QtCore/qvariantanimation.h \
		/anaconda3/include/qt/QtCore/qqueue.h \
		/anaconda3/include/qt/QtCore/qreadwritelock.h \
		/anaconda3/include/qt/QtCore/qregularexpression.h \
		/anaconda3/include/qt/QtCore/qresource.h \
		/anaconda3/include/qt/QtCore/qsavefile.h \
		/anaconda3/include/qt/QtCore/qscopedvaluerollback.h \
		/anaconda3/include/qt/QtCore/qsemaphore.h \
		/anaconda3/include/qt/QtCore/qsequentialanimationgroup.h \
		/anaconda3/include/qt/QtCore/qsettings.h \
		/anaconda3/include/qt/QtCore/qsharedmemory.h \
		/anaconda3/include/qt/QtCore/qsignalmapper.h \
		/anaconda3/include/qt/QtCore/qsignaltransition.h \
		/anaconda3/include/qt/QtCore/qsocketnotifier.h \
		/anaconda3/include/qt/QtCore/qsortfilterproxymodel.h \
		/anaconda3/include/qt/QtCore/qstack.h \
		/anaconda3/include/qt/QtCore/qstandardpaths.h \
		/anaconda3/include/qt/QtCore/qstate.h \
		/anaconda3/include/qt/QtCore/qstatemachine.h \
		/anaconda3/include/qt/QtCore/qstorageinfo.h \
		/anaconda3/include/qt/QtCore/qstringlistmodel.h \
		/anaconda3/include/qt/QtCore/qsystemsemaphore.h \
		/anaconda3/include/qt/QtCore/qtemporarydir.h \
		/anaconda3/include/qt/QtCore/QScopedPointer \
		/anaconda3/include/qt/QtCore/qtemporaryfile.h \
		/anaconda3/include/qt/QtCore/qtextboundaryfinder.h \
		/anaconda3/include/qt/QtCore/qtextcodec.h \
		/anaconda3/include/qt/QtCore/qthread.h \
		/anaconda3/include/qt/QtCore/qthreadpool.h \
		/anaconda3/include/qt/QtCore/qthreadstorage.h \
		/anaconda3/include/qt/QtCore/qtimeline.h \
		/anaconda3/include/qt/QtCore/qtimer.h \
		/anaconda3/include/qt/QtCore/qtimezone.h \
		/anaconda3/include/qt/QtCore/qtranslator.h \
		/anaconda3/include/qt/QtCore/qtypetraits.h \
		/anaconda3/include/qt/QtCore/quuid.h \
		/anaconda3/include/qt/QtCore/qwaitcondition.h \
		/anaconda3/include/qt/QtCore/qwineventnotifier.h \
		/anaconda3/include/qt/QtCore/qxmlstream.h \
		/anaconda3/include/qt/QtCore/qtcoreversion.h \
		/anaconda3/include/qt/QtGui/QtGui \
		/anaconda3/include/qt/QtGui/QtGuiDepends \
		/anaconda3/include/qt/QtGui/qabstracttextdocumentlayout.h \
		/anaconda3/include/qt/QtGui/qtextlayout.h \
		/anaconda3/include/qt/QtGui/qtextformat.h \
		/anaconda3/include/qt/QtGui/qpen.h \
		/anaconda3/include/qt/QtGui/qtextoption.h \
		/anaconda3/include/qt/QtGui/qglyphrun.h \
		/anaconda3/include/qt/QtGui/qrawfont.h \
		/anaconda3/include/qt/QtGui/qfontdatabase.h \
		/anaconda3/include/qt/QtGui/qtextcursor.h \
		/anaconda3/include/qt/QtGui/qtextdocument.h \
		/anaconda3/include/qt/QtGui/qaccessible.h \
		/anaconda3/include/qt/QtGui/qaccessiblebridge.h \
		/anaconda3/include/qt/QtGui/qaccessibleobject.h \
		/anaconda3/include/qt/QtGui/qaccessibleplugin.h \
		/anaconda3/include/qt/QtGui/qbackingstore.h \
		/anaconda3/include/qt/QtGui/qwindow.h \
		/anaconda3/include/qt/QtCore/QEvent \
		/anaconda3/include/qt/QtCore/QMargins \
		/anaconda3/include/qt/QtCore/QRect \
		/anaconda3/include/qt/QtGui/qsurface.h \
		/anaconda3/include/qt/QtGui/qsurfaceformat.h \
		/anaconda3/include/qt/QtGui/qbitmap.h \
		/anaconda3/include/qt/QtGui/qclipboard.h \
		/anaconda3/include/qt/QtGui/qdesktopservices.h \
		/anaconda3/include/qt/QtGui/qdrag.h \
		/anaconda3/include/qt/QtGui/qgenericmatrix.h \
		/anaconda3/include/qt/QtGui/qgenericplugin.h \
		/anaconda3/include/qt/QtGui/qgenericpluginfactory.h \
		/anaconda3/include/qt/QtGui/qguiapplication.h \
		/anaconda3/include/qt/QtGui/qinputmethod.h \
		/anaconda3/include/qt/QtGui/qiconengine.h \
		/anaconda3/include/qt/QtGui/qiconengineplugin.h \
		/anaconda3/include/qt/QtGui/qimageiohandler.h \
		/anaconda3/include/qt/QtGui/qimagereader.h \
		/anaconda3/include/qt/QtGui/qimagewriter.h \
		/anaconda3/include/qt/QtGui/qmatrix4x4.h \
		/anaconda3/include/qt/QtGui/qvector3d.h \
		/anaconda3/include/qt/QtGui/qvector4d.h \
		/anaconda3/include/qt/QtGui/qquaternion.h \
		/anaconda3/include/qt/QtGui/qmovie.h \
		/anaconda3/include/qt/QtGui/qoffscreensurface.h \
		/anaconda3/include/qt/QtGui/qopengl.h \
		/anaconda3/include/qt/QtCore/qt_windows.h \
		/anaconda3/include/qt/QtGui/qopengles2ext.h \
		/anaconda3/include/qt/QtGui/qopenglext.h \
		/anaconda3/include/qt/QtGui/qopenglbuffer.h \
		/anaconda3/include/qt/QtGui/qopenglcontext.h \
		/anaconda3/include/qt/QtGui/QSurfaceFormat \
		/anaconda3/include/qt/QtGui/qopenglversionfunctions.h \
		/anaconda3/include/qt/QtGui/qopengldebug.h \
		/anaconda3/include/qt/QtGui/qopenglextrafunctions.h \
		/anaconda3/include/qt/QtGui/qopenglfunctions.h \
		/anaconda3/include/qt/QtGui/qopenglframebufferobject.h \
		/anaconda3/include/qt/QtGui/qopenglpaintdevice.h \
		/anaconda3/include/qt/QtGui/qopenglpixeltransferoptions.h \
		/anaconda3/include/qt/QtCore/QSharedDataPointer \
		/anaconda3/include/qt/QtGui/qopenglshaderprogram.h \
		/anaconda3/include/qt/QtGui/qopengltexture.h \
		/anaconda3/include/qt/QtGui/qopengltextureblitter.h \
		/anaconda3/include/qt/QtGui/QMatrix3x3 \
		/anaconda3/include/qt/QtGui/QMatrix4x4 \
		/anaconda3/include/qt/QtGui/qopengltimerquery.h \
		/anaconda3/include/qt/QtGui/qopenglvertexarrayobject.h \
		/anaconda3/include/qt/QtGui/qopenglwindow.h \
		/anaconda3/include/qt/QtGui/QPaintDeviceWindow \
		/anaconda3/include/qt/QtGui/qpaintdevicewindow.h \
		/anaconda3/include/qt/QtGui/QWindow \
		/anaconda3/include/qt/QtGui/QPaintDevice \
		/anaconda3/include/qt/QtGui/QOpenGLContext \
		/anaconda3/include/qt/QtGui/QImage \
		/anaconda3/include/qt/QtGui/qpagedpaintdevice.h \
		/anaconda3/include/qt/QtGui/qpagelayout.h \
		/anaconda3/include/qt/QtGui/qpagesize.h \
		/anaconda3/include/qt/QtGui/qpaintengine.h \
		/anaconda3/include/qt/QtGui/qpainter.h \
		/anaconda3/include/qt/QtGui/qpdfwriter.h \
		/anaconda3/include/qt/QtGui/qpicture.h \
		/anaconda3/include/qt/QtGui/qpictureformatplugin.h \
		/anaconda3/include/qt/QtGui/qpixmapcache.h \
		/anaconda3/include/qt/QtGui/qrasterwindow.h \
		/anaconda3/include/qt/QtGui/qscreen.h \
		/anaconda3/include/qt/QtCore/QList \
		/anaconda3/include/qt/QtCore/QSize \
		/anaconda3/include/qt/QtCore/QSizeF \
		/anaconda3/include/qt/QtGui/QTransform \
		/anaconda3/include/qt/QtGui/qsessionmanager.h \
		/anaconda3/include/qt/QtGui/qstandarditemmodel.h \
		/anaconda3/include/qt/QtGui/qstatictext.h \
		/anaconda3/include/qt/QtGui/qstylehints.h \
		/anaconda3/include/qt/QtGui/qsyntaxhighlighter.h \
		/anaconda3/include/qt/QtGui/qtextobject.h \
		/anaconda3/include/qt/QtGui/qtextdocumentfragment.h \
		/anaconda3/include/qt/QtGui/qtextdocumentwriter.h \
		/anaconda3/include/qt/QtGui/qtextlist.h \
		/anaconda3/include/qt/QtGui/qtexttable.h \
		/anaconda3/include/qt/QtGui/qvalidator.h \
		/anaconda3/include/qt/QtGui/qtguiversion.h \
		/anaconda3/include/qt/QtWidgets/QMessageBox \
		/anaconda3/include/qt/QtWidgets/qmessagebox.h \
		/anaconda3/include/qt/QtWidgets/qdialog.h \
		gameplay.h \
		moc_predefs.h \
		/anaconda3/bin/moc
	/anaconda3/bin/moc $(DEFINES) --include ./moc_predefs.h -I/anaconda3/mkspecs/macx-clang -I/Users/jessicawu/Desktop/OthelloUI -I/Users/jessicawu/Desktop/OthelloUI -I/anaconda3/include/qt -I/anaconda3/include/qt/QtWidgets -I/anaconda3/include/qt/QtGui -I/anaconda3/include/qt/QtCore -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include gameplay.h -o moc_gameplay.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_gameplay.h
compiler_uic_clean:
	-$(DEL_FILE) ui_gameplay.h
ui_gameplay.h: gameplay.ui \
		/anaconda3/bin/uic
	/anaconda3/bin/uic gameplay.ui -o ui_gameplay.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

clickableBt.o: clickableBt.cpp clickableBt.h \
		/anaconda3/include/qt/QtWidgets/QLabel \
		/anaconda3/include/qt/QtWidgets/qlabel.h \
		/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		/anaconda3/include/qt/QtGui/qtguiglobal.h \
		/anaconda3/include/qt/QtCore/qglobal.h \
		/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/anaconda3/include/qt/QtCore/qconfig.h \
		/anaconda3/include/qt/QtCore/qtcore-config.h \
		/anaconda3/include/qt/QtCore/qsystemdetection.h \
		/anaconda3/include/qt/QtCore/qprocessordetection.h \
		/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/anaconda3/include/qt/QtCore/qtypeinfo.h \
		/anaconda3/include/qt/QtCore/qsysinfo.h \
		/anaconda3/include/qt/QtCore/qlogging.h \
		/anaconda3/include/qt/QtCore/qflags.h \
		/anaconda3/include/qt/QtCore/qatomic.h \
		/anaconda3/include/qt/QtCore/qbasicatomic.h \
		/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/anaconda3/include/qt/QtCore/qgenericatomic.h \
		/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/anaconda3/include/qt/QtCore/qglobalstatic.h \
		/anaconda3/include/qt/QtCore/qmutex.h \
		/anaconda3/include/qt/QtCore/qnumeric.h \
		/anaconda3/include/qt/QtCore/qversiontagging.h \
		/anaconda3/include/qt/QtGui/qtgui-config.h \
		/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		/anaconda3/include/qt/QtWidgets/qframe.h \
		/anaconda3/include/qt/QtWidgets/qwidget.h \
		/anaconda3/include/qt/QtGui/qwindowdefs.h \
		/anaconda3/include/qt/QtCore/qobjectdefs.h \
		/anaconda3/include/qt/QtCore/qnamespace.h \
		/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		/anaconda3/include/qt/QtCore/qobject.h \
		/anaconda3/include/qt/QtCore/qstring.h \
		/anaconda3/include/qt/QtCore/qchar.h \
		/anaconda3/include/qt/QtCore/qbytearray.h \
		/anaconda3/include/qt/QtCore/qrefcount.h \
		/anaconda3/include/qt/QtCore/qarraydata.h \
		/anaconda3/include/qt/QtCore/qstringbuilder.h \
		/anaconda3/include/qt/QtCore/qlist.h \
		/anaconda3/include/qt/QtCore/qalgorithms.h \
		/anaconda3/include/qt/QtCore/qiterator.h \
		/anaconda3/include/qt/QtCore/qhashfunctions.h \
		/anaconda3/include/qt/QtCore/qpair.h \
		/anaconda3/include/qt/QtCore/qbytearraylist.h \
		/anaconda3/include/qt/QtCore/qstringlist.h \
		/anaconda3/include/qt/QtCore/qregexp.h \
		/anaconda3/include/qt/QtCore/qstringmatcher.h \
		/anaconda3/include/qt/QtCore/qcoreevent.h \
		/anaconda3/include/qt/QtCore/qscopedpointer.h \
		/anaconda3/include/qt/QtCore/qmetatype.h \
		/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/anaconda3/include/qt/QtCore/qobject_impl.h \
		/anaconda3/include/qt/QtCore/qmargins.h \
		/anaconda3/include/qt/QtGui/qpaintdevice.h \
		/anaconda3/include/qt/QtCore/qrect.h \
		/anaconda3/include/qt/QtCore/qsize.h \
		/anaconda3/include/qt/QtCore/qpoint.h \
		/anaconda3/include/qt/QtGui/qpalette.h \
		/anaconda3/include/qt/QtGui/qcolor.h \
		/anaconda3/include/qt/QtGui/qrgb.h \
		/anaconda3/include/qt/QtGui/qrgba64.h \
		/anaconda3/include/qt/QtGui/qbrush.h \
		/anaconda3/include/qt/QtCore/qvector.h \
		/anaconda3/include/qt/QtGui/qmatrix.h \
		/anaconda3/include/qt/QtGui/qpolygon.h \
		/anaconda3/include/qt/QtGui/qregion.h \
		/anaconda3/include/qt/QtCore/qdatastream.h \
		/anaconda3/include/qt/QtCore/qiodevice.h \
		/anaconda3/include/qt/QtCore/qline.h \
		/anaconda3/include/qt/QtGui/qtransform.h \
		/anaconda3/include/qt/QtGui/qpainterpath.h \
		/anaconda3/include/qt/QtGui/qimage.h \
		/anaconda3/include/qt/QtGui/qpixelformat.h \
		/anaconda3/include/qt/QtGui/qpixmap.h \
		/anaconda3/include/qt/QtCore/qsharedpointer.h \
		/anaconda3/include/qt/QtCore/qshareddata.h \
		/anaconda3/include/qt/QtCore/qhash.h \
		/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		/anaconda3/include/qt/QtGui/qfont.h \
		/anaconda3/include/qt/QtGui/qfontmetrics.h \
		/anaconda3/include/qt/QtGui/qfontinfo.h \
		/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		/anaconda3/include/qt/QtGui/qcursor.h \
		/anaconda3/include/qt/QtGui/qkeysequence.h \
		/anaconda3/include/qt/QtGui/qevent.h \
		/anaconda3/include/qt/QtCore/qvariant.h \
		/anaconda3/include/qt/QtCore/qmap.h \
		/anaconda3/include/qt/QtCore/qdebug.h \
		/anaconda3/include/qt/QtCore/qtextstream.h \
		/anaconda3/include/qt/QtCore/qlocale.h \
		/anaconda3/include/qt/QtCore/qset.h \
		/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		/anaconda3/include/qt/QtCore/qurl.h \
		/anaconda3/include/qt/QtCore/qurlquery.h \
		/anaconda3/include/qt/QtCore/qfile.h \
		/anaconda3/include/qt/QtCore/qfiledevice.h \
		/anaconda3/include/qt/QtGui/qvector2d.h \
		/anaconda3/include/qt/QtGui/qtouchdevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clickableBt.o clickableBt.cpp

gameplay.o: gameplay.cpp gameplay.h \
		/anaconda3/include/qt/QtWidgets/QMainWindow \
		/anaconda3/include/qt/QtWidgets/qmainwindow.h \
		/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		/anaconda3/include/qt/QtGui/qtguiglobal.h \
		/anaconda3/include/qt/QtCore/qglobal.h \
		/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/anaconda3/include/qt/QtCore/qconfig.h \
		/anaconda3/include/qt/QtCore/qtcore-config.h \
		/anaconda3/include/qt/QtCore/qsystemdetection.h \
		/anaconda3/include/qt/QtCore/qprocessordetection.h \
		/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/anaconda3/include/qt/QtCore/qtypeinfo.h \
		/anaconda3/include/qt/QtCore/qsysinfo.h \
		/anaconda3/include/qt/QtCore/qlogging.h \
		/anaconda3/include/qt/QtCore/qflags.h \
		/anaconda3/include/qt/QtCore/qatomic.h \
		/anaconda3/include/qt/QtCore/qbasicatomic.h \
		/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/anaconda3/include/qt/QtCore/qgenericatomic.h \
		/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/anaconda3/include/qt/QtCore/qglobalstatic.h \
		/anaconda3/include/qt/QtCore/qmutex.h \
		/anaconda3/include/qt/QtCore/qnumeric.h \
		/anaconda3/include/qt/QtCore/qversiontagging.h \
		/anaconda3/include/qt/QtGui/qtgui-config.h \
		/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		/anaconda3/include/qt/QtWidgets/qwidget.h \
		/anaconda3/include/qt/QtGui/qwindowdefs.h \
		/anaconda3/include/qt/QtCore/qobjectdefs.h \
		/anaconda3/include/qt/QtCore/qnamespace.h \
		/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		/anaconda3/include/qt/QtCore/qobject.h \
		/anaconda3/include/qt/QtCore/qstring.h \
		/anaconda3/include/qt/QtCore/qchar.h \
		/anaconda3/include/qt/QtCore/qbytearray.h \
		/anaconda3/include/qt/QtCore/qrefcount.h \
		/anaconda3/include/qt/QtCore/qarraydata.h \
		/anaconda3/include/qt/QtCore/qstringbuilder.h \
		/anaconda3/include/qt/QtCore/qlist.h \
		/anaconda3/include/qt/QtCore/qalgorithms.h \
		/anaconda3/include/qt/QtCore/qiterator.h \
		/anaconda3/include/qt/QtCore/qhashfunctions.h \
		/anaconda3/include/qt/QtCore/qpair.h \
		/anaconda3/include/qt/QtCore/qbytearraylist.h \
		/anaconda3/include/qt/QtCore/qstringlist.h \
		/anaconda3/include/qt/QtCore/qregexp.h \
		/anaconda3/include/qt/QtCore/qstringmatcher.h \
		/anaconda3/include/qt/QtCore/qcoreevent.h \
		/anaconda3/include/qt/QtCore/qscopedpointer.h \
		/anaconda3/include/qt/QtCore/qmetatype.h \
		/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/anaconda3/include/qt/QtCore/qobject_impl.h \
		/anaconda3/include/qt/QtCore/qmargins.h \
		/anaconda3/include/qt/QtGui/qpaintdevice.h \
		/anaconda3/include/qt/QtCore/qrect.h \
		/anaconda3/include/qt/QtCore/qsize.h \
		/anaconda3/include/qt/QtCore/qpoint.h \
		/anaconda3/include/qt/QtGui/qpalette.h \
		/anaconda3/include/qt/QtGui/qcolor.h \
		/anaconda3/include/qt/QtGui/qrgb.h \
		/anaconda3/include/qt/QtGui/qrgba64.h \
		/anaconda3/include/qt/QtGui/qbrush.h \
		/anaconda3/include/qt/QtCore/qvector.h \
		/anaconda3/include/qt/QtGui/qmatrix.h \
		/anaconda3/include/qt/QtGui/qpolygon.h \
		/anaconda3/include/qt/QtGui/qregion.h \
		/anaconda3/include/qt/QtCore/qdatastream.h \
		/anaconda3/include/qt/QtCore/qiodevice.h \
		/anaconda3/include/qt/QtCore/qline.h \
		/anaconda3/include/qt/QtGui/qtransform.h \
		/anaconda3/include/qt/QtGui/qpainterpath.h \
		/anaconda3/include/qt/QtGui/qimage.h \
		/anaconda3/include/qt/QtGui/qpixelformat.h \
		/anaconda3/include/qt/QtGui/qpixmap.h \
		/anaconda3/include/qt/QtCore/qsharedpointer.h \
		/anaconda3/include/qt/QtCore/qshareddata.h \
		/anaconda3/include/qt/QtCore/qhash.h \
		/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		/anaconda3/include/qt/QtGui/qfont.h \
		/anaconda3/include/qt/QtGui/qfontmetrics.h \
		/anaconda3/include/qt/QtGui/qfontinfo.h \
		/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		/anaconda3/include/qt/QtGui/qcursor.h \
		/anaconda3/include/qt/QtGui/qkeysequence.h \
		/anaconda3/include/qt/QtGui/qevent.h \
		/anaconda3/include/qt/QtCore/qvariant.h \
		/anaconda3/include/qt/QtCore/qmap.h \
		/anaconda3/include/qt/QtCore/qdebug.h \
		/anaconda3/include/qt/QtCore/qtextstream.h \
		/anaconda3/include/qt/QtCore/qlocale.h \
		/anaconda3/include/qt/QtCore/qset.h \
		/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		/anaconda3/include/qt/QtCore/qurl.h \
		/anaconda3/include/qt/QtCore/qurlquery.h \
		/anaconda3/include/qt/QtCore/qfile.h \
		/anaconda3/include/qt/QtCore/qfiledevice.h \
		/anaconda3/include/qt/QtGui/qvector2d.h \
		/anaconda3/include/qt/QtGui/qtouchdevice.h \
		/anaconda3/include/qt/QtWidgets/qtabwidget.h \
		/anaconda3/include/qt/QtGui/qicon.h \
		logic.h \
		/anaconda3/include/qt/QtGui/QPixmap \
		clickableBt.h \
		/anaconda3/include/qt/QtWidgets/QLabel \
		/anaconda3/include/qt/QtWidgets/qlabel.h \
		/anaconda3/include/qt/QtWidgets/qframe.h \
		ui_gameplay.h \
		/anaconda3/include/qt/QtCore/QtCore \
		/anaconda3/include/qt/QtCore/QtCoreDepends \
		/anaconda3/include/qt/QtCore/qabstractanimation.h \
		/anaconda3/include/qt/QtCore/qabstracteventdispatcher.h \
		/anaconda3/include/qt/QtCore/qeventloop.h \
		/anaconda3/include/qt/QtCore/qabstractitemmodel.h \
		/anaconda3/include/qt/QtCore/qabstractnativeeventfilter.h \
		/anaconda3/include/qt/QtCore/qabstractproxymodel.h \
		/anaconda3/include/qt/QtCore/qabstractstate.h \
		/anaconda3/include/qt/QtCore/qabstracttransition.h \
		/anaconda3/include/qt/QtCore/qanimationgroup.h \
		/anaconda3/include/qt/QtCore/qarraydataops.h \
		/anaconda3/include/qt/QtCore/qarraydatapointer.h \
		/anaconda3/include/qt/QtCore/qbasictimer.h \
		/anaconda3/include/qt/QtCore/qbitarray.h \
		/anaconda3/include/qt/QtCore/qbuffer.h \
		/anaconda3/include/qt/QtCore/qbytearraymatcher.h \
		/anaconda3/include/qt/QtCore/qcache.h \
		/anaconda3/include/qt/QtCore/qcollator.h \
		/anaconda3/include/qt/QtCore/qcommandlineoption.h \
		/anaconda3/include/qt/QtCore/qcommandlineparser.h \
		/anaconda3/include/qt/QtCore/qcoreapplication.h \
		/anaconda3/include/qt/QtCore/qcryptographichash.h \
		/anaconda3/include/qt/QtCore/qdatetime.h \
		/anaconda3/include/qt/QtCore/qdeadlinetimer.h \
		/anaconda3/include/qt/QtCore/qelapsedtimer.h \
		/anaconda3/include/qt/QtCore/qdir.h \
		/anaconda3/include/qt/QtCore/qfileinfo.h \
		/anaconda3/include/qt/QtCore/qdiriterator.h \
		/anaconda3/include/qt/QtCore/qeasingcurve.h \
		/anaconda3/include/qt/QtCore/qendian.h \
		/anaconda3/include/qt/QtCore/qeventtransition.h \
		/anaconda3/include/qt/QtCore/qexception.h \
		/anaconda3/include/qt/QtCore/qfactoryinterface.h \
		/anaconda3/include/qt/QtCore/qfileselector.h \
		/anaconda3/include/qt/QtCore/QObject \
		/anaconda3/include/qt/QtCore/QStringList \
		/anaconda3/include/qt/QtCore/qfilesystemwatcher.h \
		/anaconda3/include/qt/QtCore/qfinalstate.h \
		/anaconda3/include/qt/QtCore/qfuture.h \
		/anaconda3/include/qt/QtCore/qfutureinterface.h \
		/anaconda3/include/qt/QtCore/qrunnable.h \
		/anaconda3/include/qt/QtCore/qresultstore.h \
		/anaconda3/include/qt/QtCore/qfuturesynchronizer.h \
		/anaconda3/include/qt/QtCore/qfuturewatcher.h \
		/anaconda3/include/qt/QtCore/qhistorystate.h \
		/anaconda3/include/qt/QtCore/qidentityproxymodel.h \
		/anaconda3/include/qt/QtCore/qisenum.h \
		/anaconda3/include/qt/QtCore/qitemselectionmodel.h \
		/anaconda3/include/qt/QtCore/qjsonarray.h \
		/anaconda3/include/qt/QtCore/qjsonvalue.h \
		/anaconda3/include/qt/QtCore/qjsondocument.h \
		/anaconda3/include/qt/QtCore/qjsonobject.h \
		/anaconda3/include/qt/QtCore/qlibrary.h \
		/anaconda3/include/qt/QtCore/qlibraryinfo.h \
		/anaconda3/include/qt/QtCore/qversionnumber.h \
		/anaconda3/include/qt/QtCore/qlinkedlist.h \
		/anaconda3/include/qt/QtCore/qlockfile.h \
		/anaconda3/include/qt/QtCore/qloggingcategory.h \
		/anaconda3/include/qt/QtCore/qmath.h \
		/anaconda3/include/qt/QtCore/qmessageauthenticationcode.h \
		/anaconda3/include/qt/QtCore/qmetaobject.h \
		/anaconda3/include/qt/QtCore/qmimedata.h \
		/anaconda3/include/qt/QtCore/qmimedatabase.h \
		/anaconda3/include/qt/QtCore/qmimetype.h \
		/anaconda3/include/qt/QtCore/qobjectcleanuphandler.h \
		/anaconda3/include/qt/QtCore/qoperatingsystemversion.h \
		/anaconda3/include/qt/QtCore/qparallelanimationgroup.h \
		/anaconda3/include/qt/QtCore/qpauseanimation.h \
		/anaconda3/include/qt/QtCore/qplugin.h \
		/anaconda3/include/qt/QtCore/qpointer.h \
		/anaconda3/include/qt/QtCore/qpluginloader.h \
		/anaconda3/include/qt/QtCore/qprocess.h \
		/anaconda3/include/qt/QtCore/qpropertyanimation.h \
		/anaconda3/include/qt/QtCore/qvariantanimation.h \
		/anaconda3/include/qt/QtCore/qqueue.h \
		/anaconda3/include/qt/QtCore/qreadwritelock.h \
		/anaconda3/include/qt/QtCore/qregularexpression.h \
		/anaconda3/include/qt/QtCore/qresource.h \
		/anaconda3/include/qt/QtCore/qsavefile.h \
		/anaconda3/include/qt/QtCore/qscopedvaluerollback.h \
		/anaconda3/include/qt/QtCore/qsemaphore.h \
		/anaconda3/include/qt/QtCore/qsequentialanimationgroup.h \
		/anaconda3/include/qt/QtCore/qsettings.h \
		/anaconda3/include/qt/QtCore/qsharedmemory.h \
		/anaconda3/include/qt/QtCore/qsignalmapper.h \
		/anaconda3/include/qt/QtCore/qsignaltransition.h \
		/anaconda3/include/qt/QtCore/qsocketnotifier.h \
		/anaconda3/include/qt/QtCore/qsortfilterproxymodel.h \
		/anaconda3/include/qt/QtCore/qstack.h \
		/anaconda3/include/qt/QtCore/qstandardpaths.h \
		/anaconda3/include/qt/QtCore/qstate.h \
		/anaconda3/include/qt/QtCore/qstatemachine.h \
		/anaconda3/include/qt/QtCore/qstorageinfo.h \
		/anaconda3/include/qt/QtCore/qstringlistmodel.h \
		/anaconda3/include/qt/QtCore/qsystemsemaphore.h \
		/anaconda3/include/qt/QtCore/qtemporarydir.h \
		/anaconda3/include/qt/QtCore/QScopedPointer \
		/anaconda3/include/qt/QtCore/qtemporaryfile.h \
		/anaconda3/include/qt/QtCore/qtextboundaryfinder.h \
		/anaconda3/include/qt/QtCore/qtextcodec.h \
		/anaconda3/include/qt/QtCore/qthread.h \
		/anaconda3/include/qt/QtCore/qthreadpool.h \
		/anaconda3/include/qt/QtCore/qthreadstorage.h \
		/anaconda3/include/qt/QtCore/qtimeline.h \
		/anaconda3/include/qt/QtCore/qtimer.h \
		/anaconda3/include/qt/QtCore/qtimezone.h \
		/anaconda3/include/qt/QtCore/qtranslator.h \
		/anaconda3/include/qt/QtCore/qtypetraits.h \
		/anaconda3/include/qt/QtCore/quuid.h \
		/anaconda3/include/qt/QtCore/qwaitcondition.h \
		/anaconda3/include/qt/QtCore/qwineventnotifier.h \
		/anaconda3/include/qt/QtCore/qxmlstream.h \
		/anaconda3/include/qt/QtCore/qtcoreversion.h \
		/anaconda3/include/qt/QtGui/QtGui \
		/anaconda3/include/qt/QtGui/QtGuiDepends \
		/anaconda3/include/qt/QtGui/qabstracttextdocumentlayout.h \
		/anaconda3/include/qt/QtGui/qtextlayout.h \
		/anaconda3/include/qt/QtGui/qtextformat.h \
		/anaconda3/include/qt/QtGui/qpen.h \
		/anaconda3/include/qt/QtGui/qtextoption.h \
		/anaconda3/include/qt/QtGui/qglyphrun.h \
		/anaconda3/include/qt/QtGui/qrawfont.h \
		/anaconda3/include/qt/QtGui/qfontdatabase.h \
		/anaconda3/include/qt/QtGui/qtextcursor.h \
		/anaconda3/include/qt/QtGui/qtextdocument.h \
		/anaconda3/include/qt/QtGui/qaccessible.h \
		/anaconda3/include/qt/QtGui/qaccessiblebridge.h \
		/anaconda3/include/qt/QtGui/qaccessibleobject.h \
		/anaconda3/include/qt/QtGui/qaccessibleplugin.h \
		/anaconda3/include/qt/QtGui/qbackingstore.h \
		/anaconda3/include/qt/QtGui/qwindow.h \
		/anaconda3/include/qt/QtCore/QEvent \
		/anaconda3/include/qt/QtCore/QMargins \
		/anaconda3/include/qt/QtCore/QRect \
		/anaconda3/include/qt/QtGui/qsurface.h \
		/anaconda3/include/qt/QtGui/qsurfaceformat.h \
		/anaconda3/include/qt/QtGui/qbitmap.h \
		/anaconda3/include/qt/QtGui/qclipboard.h \
		/anaconda3/include/qt/QtGui/qdesktopservices.h \
		/anaconda3/include/qt/QtGui/qdrag.h \
		/anaconda3/include/qt/QtGui/qgenericmatrix.h \
		/anaconda3/include/qt/QtGui/qgenericplugin.h \
		/anaconda3/include/qt/QtGui/qgenericpluginfactory.h \
		/anaconda3/include/qt/QtGui/qguiapplication.h \
		/anaconda3/include/qt/QtGui/qinputmethod.h \
		/anaconda3/include/qt/QtGui/qiconengine.h \
		/anaconda3/include/qt/QtGui/qiconengineplugin.h \
		/anaconda3/include/qt/QtGui/qimageiohandler.h \
		/anaconda3/include/qt/QtGui/qimagereader.h \
		/anaconda3/include/qt/QtGui/qimagewriter.h \
		/anaconda3/include/qt/QtGui/qmatrix4x4.h \
		/anaconda3/include/qt/QtGui/qvector3d.h \
		/anaconda3/include/qt/QtGui/qvector4d.h \
		/anaconda3/include/qt/QtGui/qquaternion.h \
		/anaconda3/include/qt/QtGui/qmovie.h \
		/anaconda3/include/qt/QtGui/qoffscreensurface.h \
		/anaconda3/include/qt/QtGui/qopengl.h \
		/anaconda3/include/qt/QtCore/qt_windows.h \
		/anaconda3/include/qt/QtGui/qopengles2ext.h \
		/anaconda3/include/qt/QtGui/qopenglext.h \
		/anaconda3/include/qt/QtGui/qopenglbuffer.h \
		/anaconda3/include/qt/QtGui/qopenglcontext.h \
		/anaconda3/include/qt/QtGui/QSurfaceFormat \
		/anaconda3/include/qt/QtGui/qopenglversionfunctions.h \
		/anaconda3/include/qt/QtGui/qopengldebug.h \
		/anaconda3/include/qt/QtGui/qopenglextrafunctions.h \
		/anaconda3/include/qt/QtGui/qopenglfunctions.h \
		/anaconda3/include/qt/QtGui/qopenglframebufferobject.h \
		/anaconda3/include/qt/QtGui/qopenglpaintdevice.h \
		/anaconda3/include/qt/QtGui/qopenglpixeltransferoptions.h \
		/anaconda3/include/qt/QtCore/QSharedDataPointer \
		/anaconda3/include/qt/QtGui/qopenglshaderprogram.h \
		/anaconda3/include/qt/QtGui/qopengltexture.h \
		/anaconda3/include/qt/QtGui/qopengltextureblitter.h \
		/anaconda3/include/qt/QtGui/QMatrix3x3 \
		/anaconda3/include/qt/QtGui/QMatrix4x4 \
		/anaconda3/include/qt/QtGui/qopengltimerquery.h \
		/anaconda3/include/qt/QtGui/qopenglvertexarrayobject.h \
		/anaconda3/include/qt/QtGui/qopenglwindow.h \
		/anaconda3/include/qt/QtGui/QPaintDeviceWindow \
		/anaconda3/include/qt/QtGui/qpaintdevicewindow.h \
		/anaconda3/include/qt/QtGui/QWindow \
		/anaconda3/include/qt/QtGui/QPaintDevice \
		/anaconda3/include/qt/QtGui/QOpenGLContext \
		/anaconda3/include/qt/QtGui/QImage \
		/anaconda3/include/qt/QtGui/qpagedpaintdevice.h \
		/anaconda3/include/qt/QtGui/qpagelayout.h \
		/anaconda3/include/qt/QtGui/qpagesize.h \
		/anaconda3/include/qt/QtGui/qpaintengine.h \
		/anaconda3/include/qt/QtGui/qpainter.h \
		/anaconda3/include/qt/QtGui/qpdfwriter.h \
		/anaconda3/include/qt/QtGui/qpicture.h \
		/anaconda3/include/qt/QtGui/qpictureformatplugin.h \
		/anaconda3/include/qt/QtGui/qpixmapcache.h \
		/anaconda3/include/qt/QtGui/qrasterwindow.h \
		/anaconda3/include/qt/QtGui/qscreen.h \
		/anaconda3/include/qt/QtCore/QList \
		/anaconda3/include/qt/QtCore/QSize \
		/anaconda3/include/qt/QtCore/QSizeF \
		/anaconda3/include/qt/QtGui/QTransform \
		/anaconda3/include/qt/QtGui/qsessionmanager.h \
		/anaconda3/include/qt/QtGui/qstandarditemmodel.h \
		/anaconda3/include/qt/QtGui/qstatictext.h \
		/anaconda3/include/qt/QtGui/qstylehints.h \
		/anaconda3/include/qt/QtGui/qsyntaxhighlighter.h \
		/anaconda3/include/qt/QtGui/qtextobject.h \
		/anaconda3/include/qt/QtGui/qtextdocumentfragment.h \
		/anaconda3/include/qt/QtGui/qtextdocumentwriter.h \
		/anaconda3/include/qt/QtGui/qtextlist.h \
		/anaconda3/include/qt/QtGui/qtexttable.h \
		/anaconda3/include/qt/QtGui/qvalidator.h \
		/anaconda3/include/qt/QtGui/qtguiversion.h \
		/anaconda3/include/qt/QtWidgets/QMessageBox \
		/anaconda3/include/qt/QtWidgets/qmessagebox.h \
		/anaconda3/include/qt/QtWidgets/qdialog.h \
		/anaconda3/include/qt/QtWidgets/QLayout \
		/anaconda3/include/qt/QtWidgets/qlayout.h \
		/anaconda3/include/qt/QtWidgets/qlayoutitem.h \
		/anaconda3/include/qt/QtWidgets/qboxlayout.h \
		/anaconda3/include/qt/QtWidgets/qgridlayout.h \
		/anaconda3/include/qt/QtWidgets/QFormLayout \
		/anaconda3/include/qt/QtWidgets/qformlayout.h \
		/anaconda3/include/qt/QtWidgets/QFileDialog \
		/anaconda3/include/qt/QtWidgets/qfiledialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gameplay.o gameplay.cpp

logic.o: logic.cpp logic.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logic.o logic.cpp

main.o: main.cpp gameplay.h \
		/anaconda3/include/qt/QtWidgets/QMainWindow \
		/anaconda3/include/qt/QtWidgets/qmainwindow.h \
		/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		/anaconda3/include/qt/QtGui/qtguiglobal.h \
		/anaconda3/include/qt/QtCore/qglobal.h \
		/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/anaconda3/include/qt/QtCore/qconfig.h \
		/anaconda3/include/qt/QtCore/qtcore-config.h \
		/anaconda3/include/qt/QtCore/qsystemdetection.h \
		/anaconda3/include/qt/QtCore/qprocessordetection.h \
		/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/anaconda3/include/qt/QtCore/qtypeinfo.h \
		/anaconda3/include/qt/QtCore/qsysinfo.h \
		/anaconda3/include/qt/QtCore/qlogging.h \
		/anaconda3/include/qt/QtCore/qflags.h \
		/anaconda3/include/qt/QtCore/qatomic.h \
		/anaconda3/include/qt/QtCore/qbasicatomic.h \
		/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/anaconda3/include/qt/QtCore/qgenericatomic.h \
		/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/anaconda3/include/qt/QtCore/qglobalstatic.h \
		/anaconda3/include/qt/QtCore/qmutex.h \
		/anaconda3/include/qt/QtCore/qnumeric.h \
		/anaconda3/include/qt/QtCore/qversiontagging.h \
		/anaconda3/include/qt/QtGui/qtgui-config.h \
		/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		/anaconda3/include/qt/QtWidgets/qwidget.h \
		/anaconda3/include/qt/QtGui/qwindowdefs.h \
		/anaconda3/include/qt/QtCore/qobjectdefs.h \
		/anaconda3/include/qt/QtCore/qnamespace.h \
		/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		/anaconda3/include/qt/QtCore/qobject.h \
		/anaconda3/include/qt/QtCore/qstring.h \
		/anaconda3/include/qt/QtCore/qchar.h \
		/anaconda3/include/qt/QtCore/qbytearray.h \
		/anaconda3/include/qt/QtCore/qrefcount.h \
		/anaconda3/include/qt/QtCore/qarraydata.h \
		/anaconda3/include/qt/QtCore/qstringbuilder.h \
		/anaconda3/include/qt/QtCore/qlist.h \
		/anaconda3/include/qt/QtCore/qalgorithms.h \
		/anaconda3/include/qt/QtCore/qiterator.h \
		/anaconda3/include/qt/QtCore/qhashfunctions.h \
		/anaconda3/include/qt/QtCore/qpair.h \
		/anaconda3/include/qt/QtCore/qbytearraylist.h \
		/anaconda3/include/qt/QtCore/qstringlist.h \
		/anaconda3/include/qt/QtCore/qregexp.h \
		/anaconda3/include/qt/QtCore/qstringmatcher.h \
		/anaconda3/include/qt/QtCore/qcoreevent.h \
		/anaconda3/include/qt/QtCore/qscopedpointer.h \
		/anaconda3/include/qt/QtCore/qmetatype.h \
		/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/anaconda3/include/qt/QtCore/qobject_impl.h \
		/anaconda3/include/qt/QtCore/qmargins.h \
		/anaconda3/include/qt/QtGui/qpaintdevice.h \
		/anaconda3/include/qt/QtCore/qrect.h \
		/anaconda3/include/qt/QtCore/qsize.h \
		/anaconda3/include/qt/QtCore/qpoint.h \
		/anaconda3/include/qt/QtGui/qpalette.h \
		/anaconda3/include/qt/QtGui/qcolor.h \
		/anaconda3/include/qt/QtGui/qrgb.h \
		/anaconda3/include/qt/QtGui/qrgba64.h \
		/anaconda3/include/qt/QtGui/qbrush.h \
		/anaconda3/include/qt/QtCore/qvector.h \
		/anaconda3/include/qt/QtGui/qmatrix.h \
		/anaconda3/include/qt/QtGui/qpolygon.h \
		/anaconda3/include/qt/QtGui/qregion.h \
		/anaconda3/include/qt/QtCore/qdatastream.h \
		/anaconda3/include/qt/QtCore/qiodevice.h \
		/anaconda3/include/qt/QtCore/qline.h \
		/anaconda3/include/qt/QtGui/qtransform.h \
		/anaconda3/include/qt/QtGui/qpainterpath.h \
		/anaconda3/include/qt/QtGui/qimage.h \
		/anaconda3/include/qt/QtGui/qpixelformat.h \
		/anaconda3/include/qt/QtGui/qpixmap.h \
		/anaconda3/include/qt/QtCore/qsharedpointer.h \
		/anaconda3/include/qt/QtCore/qshareddata.h \
		/anaconda3/include/qt/QtCore/qhash.h \
		/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		/anaconda3/include/qt/QtGui/qfont.h \
		/anaconda3/include/qt/QtGui/qfontmetrics.h \
		/anaconda3/include/qt/QtGui/qfontinfo.h \
		/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		/anaconda3/include/qt/QtGui/qcursor.h \
		/anaconda3/include/qt/QtGui/qkeysequence.h \
		/anaconda3/include/qt/QtGui/qevent.h \
		/anaconda3/include/qt/QtCore/qvariant.h \
		/anaconda3/include/qt/QtCore/qmap.h \
		/anaconda3/include/qt/QtCore/qdebug.h \
		/anaconda3/include/qt/QtCore/qtextstream.h \
		/anaconda3/include/qt/QtCore/qlocale.h \
		/anaconda3/include/qt/QtCore/qset.h \
		/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		/anaconda3/include/qt/QtCore/qurl.h \
		/anaconda3/include/qt/QtCore/qurlquery.h \
		/anaconda3/include/qt/QtCore/qfile.h \
		/anaconda3/include/qt/QtCore/qfiledevice.h \
		/anaconda3/include/qt/QtGui/qvector2d.h \
		/anaconda3/include/qt/QtGui/qtouchdevice.h \
		/anaconda3/include/qt/QtWidgets/qtabwidget.h \
		/anaconda3/include/qt/QtGui/qicon.h \
		logic.h \
		/anaconda3/include/qt/QtGui/QPixmap \
		clickableBt.h \
		/anaconda3/include/qt/QtWidgets/QLabel \
		/anaconda3/include/qt/QtWidgets/qlabel.h \
		/anaconda3/include/qt/QtWidgets/qframe.h \
		ui_gameplay.h \
		/anaconda3/include/qt/QtCore/QtCore \
		/anaconda3/include/qt/QtCore/QtCoreDepends \
		/anaconda3/include/qt/QtCore/qabstractanimation.h \
		/anaconda3/include/qt/QtCore/qabstracteventdispatcher.h \
		/anaconda3/include/qt/QtCore/qeventloop.h \
		/anaconda3/include/qt/QtCore/qabstractitemmodel.h \
		/anaconda3/include/qt/QtCore/qabstractnativeeventfilter.h \
		/anaconda3/include/qt/QtCore/qabstractproxymodel.h \
		/anaconda3/include/qt/QtCore/qabstractstate.h \
		/anaconda3/include/qt/QtCore/qabstracttransition.h \
		/anaconda3/include/qt/QtCore/qanimationgroup.h \
		/anaconda3/include/qt/QtCore/qarraydataops.h \
		/anaconda3/include/qt/QtCore/qarraydatapointer.h \
		/anaconda3/include/qt/QtCore/qbasictimer.h \
		/anaconda3/include/qt/QtCore/qbitarray.h \
		/anaconda3/include/qt/QtCore/qbuffer.h \
		/anaconda3/include/qt/QtCore/qbytearraymatcher.h \
		/anaconda3/include/qt/QtCore/qcache.h \
		/anaconda3/include/qt/QtCore/qcollator.h \
		/anaconda3/include/qt/QtCore/qcommandlineoption.h \
		/anaconda3/include/qt/QtCore/qcommandlineparser.h \
		/anaconda3/include/qt/QtCore/qcoreapplication.h \
		/anaconda3/include/qt/QtCore/qcryptographichash.h \
		/anaconda3/include/qt/QtCore/qdatetime.h \
		/anaconda3/include/qt/QtCore/qdeadlinetimer.h \
		/anaconda3/include/qt/QtCore/qelapsedtimer.h \
		/anaconda3/include/qt/QtCore/qdir.h \
		/anaconda3/include/qt/QtCore/qfileinfo.h \
		/anaconda3/include/qt/QtCore/qdiriterator.h \
		/anaconda3/include/qt/QtCore/qeasingcurve.h \
		/anaconda3/include/qt/QtCore/qendian.h \
		/anaconda3/include/qt/QtCore/qeventtransition.h \
		/anaconda3/include/qt/QtCore/qexception.h \
		/anaconda3/include/qt/QtCore/qfactoryinterface.h \
		/anaconda3/include/qt/QtCore/qfileselector.h \
		/anaconda3/include/qt/QtCore/QObject \
		/anaconda3/include/qt/QtCore/QStringList \
		/anaconda3/include/qt/QtCore/qfilesystemwatcher.h \
		/anaconda3/include/qt/QtCore/qfinalstate.h \
		/anaconda3/include/qt/QtCore/qfuture.h \
		/anaconda3/include/qt/QtCore/qfutureinterface.h \
		/anaconda3/include/qt/QtCore/qrunnable.h \
		/anaconda3/include/qt/QtCore/qresultstore.h \
		/anaconda3/include/qt/QtCore/qfuturesynchronizer.h \
		/anaconda3/include/qt/QtCore/qfuturewatcher.h \
		/anaconda3/include/qt/QtCore/qhistorystate.h \
		/anaconda3/include/qt/QtCore/qidentityproxymodel.h \
		/anaconda3/include/qt/QtCore/qisenum.h \
		/anaconda3/include/qt/QtCore/qitemselectionmodel.h \
		/anaconda3/include/qt/QtCore/qjsonarray.h \
		/anaconda3/include/qt/QtCore/qjsonvalue.h \
		/anaconda3/include/qt/QtCore/qjsondocument.h \
		/anaconda3/include/qt/QtCore/qjsonobject.h \
		/anaconda3/include/qt/QtCore/qlibrary.h \
		/anaconda3/include/qt/QtCore/qlibraryinfo.h \
		/anaconda3/include/qt/QtCore/qversionnumber.h \
		/anaconda3/include/qt/QtCore/qlinkedlist.h \
		/anaconda3/include/qt/QtCore/qlockfile.h \
		/anaconda3/include/qt/QtCore/qloggingcategory.h \
		/anaconda3/include/qt/QtCore/qmath.h \
		/anaconda3/include/qt/QtCore/qmessageauthenticationcode.h \
		/anaconda3/include/qt/QtCore/qmetaobject.h \
		/anaconda3/include/qt/QtCore/qmimedata.h \
		/anaconda3/include/qt/QtCore/qmimedatabase.h \
		/anaconda3/include/qt/QtCore/qmimetype.h \
		/anaconda3/include/qt/QtCore/qobjectcleanuphandler.h \
		/anaconda3/include/qt/QtCore/qoperatingsystemversion.h \
		/anaconda3/include/qt/QtCore/qparallelanimationgroup.h \
		/anaconda3/include/qt/QtCore/qpauseanimation.h \
		/anaconda3/include/qt/QtCore/qplugin.h \
		/anaconda3/include/qt/QtCore/qpointer.h \
		/anaconda3/include/qt/QtCore/qpluginloader.h \
		/anaconda3/include/qt/QtCore/qprocess.h \
		/anaconda3/include/qt/QtCore/qpropertyanimation.h \
		/anaconda3/include/qt/QtCore/qvariantanimation.h \
		/anaconda3/include/qt/QtCore/qqueue.h \
		/anaconda3/include/qt/QtCore/qreadwritelock.h \
		/anaconda3/include/qt/QtCore/qregularexpression.h \
		/anaconda3/include/qt/QtCore/qresource.h \
		/anaconda3/include/qt/QtCore/qsavefile.h \
		/anaconda3/include/qt/QtCore/qscopedvaluerollback.h \
		/anaconda3/include/qt/QtCore/qsemaphore.h \
		/anaconda3/include/qt/QtCore/qsequentialanimationgroup.h \
		/anaconda3/include/qt/QtCore/qsettings.h \
		/anaconda3/include/qt/QtCore/qsharedmemory.h \
		/anaconda3/include/qt/QtCore/qsignalmapper.h \
		/anaconda3/include/qt/QtCore/qsignaltransition.h \
		/anaconda3/include/qt/QtCore/qsocketnotifier.h \
		/anaconda3/include/qt/QtCore/qsortfilterproxymodel.h \
		/anaconda3/include/qt/QtCore/qstack.h \
		/anaconda3/include/qt/QtCore/qstandardpaths.h \
		/anaconda3/include/qt/QtCore/qstate.h \
		/anaconda3/include/qt/QtCore/qstatemachine.h \
		/anaconda3/include/qt/QtCore/qstorageinfo.h \
		/anaconda3/include/qt/QtCore/qstringlistmodel.h \
		/anaconda3/include/qt/QtCore/qsystemsemaphore.h \
		/anaconda3/include/qt/QtCore/qtemporarydir.h \
		/anaconda3/include/qt/QtCore/QScopedPointer \
		/anaconda3/include/qt/QtCore/qtemporaryfile.h \
		/anaconda3/include/qt/QtCore/qtextboundaryfinder.h \
		/anaconda3/include/qt/QtCore/qtextcodec.h \
		/anaconda3/include/qt/QtCore/qthread.h \
		/anaconda3/include/qt/QtCore/qthreadpool.h \
		/anaconda3/include/qt/QtCore/qthreadstorage.h \
		/anaconda3/include/qt/QtCore/qtimeline.h \
		/anaconda3/include/qt/QtCore/qtimer.h \
		/anaconda3/include/qt/QtCore/qtimezone.h \
		/anaconda3/include/qt/QtCore/qtranslator.h \
		/anaconda3/include/qt/QtCore/qtypetraits.h \
		/anaconda3/include/qt/QtCore/quuid.h \
		/anaconda3/include/qt/QtCore/qwaitcondition.h \
		/anaconda3/include/qt/QtCore/qwineventnotifier.h \
		/anaconda3/include/qt/QtCore/qxmlstream.h \
		/anaconda3/include/qt/QtCore/qtcoreversion.h \
		/anaconda3/include/qt/QtGui/QtGui \
		/anaconda3/include/qt/QtGui/QtGuiDepends \
		/anaconda3/include/qt/QtGui/qabstracttextdocumentlayout.h \
		/anaconda3/include/qt/QtGui/qtextlayout.h \
		/anaconda3/include/qt/QtGui/qtextformat.h \
		/anaconda3/include/qt/QtGui/qpen.h \
		/anaconda3/include/qt/QtGui/qtextoption.h \
		/anaconda3/include/qt/QtGui/qglyphrun.h \
		/anaconda3/include/qt/QtGui/qrawfont.h \
		/anaconda3/include/qt/QtGui/qfontdatabase.h \
		/anaconda3/include/qt/QtGui/qtextcursor.h \
		/anaconda3/include/qt/QtGui/qtextdocument.h \
		/anaconda3/include/qt/QtGui/qaccessible.h \
		/anaconda3/include/qt/QtGui/qaccessiblebridge.h \
		/anaconda3/include/qt/QtGui/qaccessibleobject.h \
		/anaconda3/include/qt/QtGui/qaccessibleplugin.h \
		/anaconda3/include/qt/QtGui/qbackingstore.h \
		/anaconda3/include/qt/QtGui/qwindow.h \
		/anaconda3/include/qt/QtCore/QEvent \
		/anaconda3/include/qt/QtCore/QMargins \
		/anaconda3/include/qt/QtCore/QRect \
		/anaconda3/include/qt/QtGui/qsurface.h \
		/anaconda3/include/qt/QtGui/qsurfaceformat.h \
		/anaconda3/include/qt/QtGui/qbitmap.h \
		/anaconda3/include/qt/QtGui/qclipboard.h \
		/anaconda3/include/qt/QtGui/qdesktopservices.h \
		/anaconda3/include/qt/QtGui/qdrag.h \
		/anaconda3/include/qt/QtGui/qgenericmatrix.h \
		/anaconda3/include/qt/QtGui/qgenericplugin.h \
		/anaconda3/include/qt/QtGui/qgenericpluginfactory.h \
		/anaconda3/include/qt/QtGui/qguiapplication.h \
		/anaconda3/include/qt/QtGui/qinputmethod.h \
		/anaconda3/include/qt/QtGui/qiconengine.h \
		/anaconda3/include/qt/QtGui/qiconengineplugin.h \
		/anaconda3/include/qt/QtGui/qimageiohandler.h \
		/anaconda3/include/qt/QtGui/qimagereader.h \
		/anaconda3/include/qt/QtGui/qimagewriter.h \
		/anaconda3/include/qt/QtGui/qmatrix4x4.h \
		/anaconda3/include/qt/QtGui/qvector3d.h \
		/anaconda3/include/qt/QtGui/qvector4d.h \
		/anaconda3/include/qt/QtGui/qquaternion.h \
		/anaconda3/include/qt/QtGui/qmovie.h \
		/anaconda3/include/qt/QtGui/qoffscreensurface.h \
		/anaconda3/include/qt/QtGui/qopengl.h \
		/anaconda3/include/qt/QtCore/qt_windows.h \
		/anaconda3/include/qt/QtGui/qopengles2ext.h \
		/anaconda3/include/qt/QtGui/qopenglext.h \
		/anaconda3/include/qt/QtGui/qopenglbuffer.h \
		/anaconda3/include/qt/QtGui/qopenglcontext.h \
		/anaconda3/include/qt/QtGui/QSurfaceFormat \
		/anaconda3/include/qt/QtGui/qopenglversionfunctions.h \
		/anaconda3/include/qt/QtGui/qopengldebug.h \
		/anaconda3/include/qt/QtGui/qopenglextrafunctions.h \
		/anaconda3/include/qt/QtGui/qopenglfunctions.h \
		/anaconda3/include/qt/QtGui/qopenglframebufferobject.h \
		/anaconda3/include/qt/QtGui/qopenglpaintdevice.h \
		/anaconda3/include/qt/QtGui/qopenglpixeltransferoptions.h \
		/anaconda3/include/qt/QtCore/QSharedDataPointer \
		/anaconda3/include/qt/QtGui/qopenglshaderprogram.h \
		/anaconda3/include/qt/QtGui/qopengltexture.h \
		/anaconda3/include/qt/QtGui/qopengltextureblitter.h \
		/anaconda3/include/qt/QtGui/QMatrix3x3 \
		/anaconda3/include/qt/QtGui/QMatrix4x4 \
		/anaconda3/include/qt/QtGui/qopengltimerquery.h \
		/anaconda3/include/qt/QtGui/qopenglvertexarrayobject.h \
		/anaconda3/include/qt/QtGui/qopenglwindow.h \
		/anaconda3/include/qt/QtGui/QPaintDeviceWindow \
		/anaconda3/include/qt/QtGui/qpaintdevicewindow.h \
		/anaconda3/include/qt/QtGui/QWindow \
		/anaconda3/include/qt/QtGui/QPaintDevice \
		/anaconda3/include/qt/QtGui/QOpenGLContext \
		/anaconda3/include/qt/QtGui/QImage \
		/anaconda3/include/qt/QtGui/qpagedpaintdevice.h \
		/anaconda3/include/qt/QtGui/qpagelayout.h \
		/anaconda3/include/qt/QtGui/qpagesize.h \
		/anaconda3/include/qt/QtGui/qpaintengine.h \
		/anaconda3/include/qt/QtGui/qpainter.h \
		/anaconda3/include/qt/QtGui/qpdfwriter.h \
		/anaconda3/include/qt/QtGui/qpicture.h \
		/anaconda3/include/qt/QtGui/qpictureformatplugin.h \
		/anaconda3/include/qt/QtGui/qpixmapcache.h \
		/anaconda3/include/qt/QtGui/qrasterwindow.h \
		/anaconda3/include/qt/QtGui/qscreen.h \
		/anaconda3/include/qt/QtCore/QList \
		/anaconda3/include/qt/QtCore/QSize \
		/anaconda3/include/qt/QtCore/QSizeF \
		/anaconda3/include/qt/QtGui/QTransform \
		/anaconda3/include/qt/QtGui/qsessionmanager.h \
		/anaconda3/include/qt/QtGui/qstandarditemmodel.h \
		/anaconda3/include/qt/QtGui/qstatictext.h \
		/anaconda3/include/qt/QtGui/qstylehints.h \
		/anaconda3/include/qt/QtGui/qsyntaxhighlighter.h \
		/anaconda3/include/qt/QtGui/qtextobject.h \
		/anaconda3/include/qt/QtGui/qtextdocumentfragment.h \
		/anaconda3/include/qt/QtGui/qtextdocumentwriter.h \
		/anaconda3/include/qt/QtGui/qtextlist.h \
		/anaconda3/include/qt/QtGui/qtexttable.h \
		/anaconda3/include/qt/QtGui/qvalidator.h \
		/anaconda3/include/qt/QtGui/qtguiversion.h \
		/anaconda3/include/qt/QtWidgets/QMessageBox \
		/anaconda3/include/qt/QtWidgets/qmessagebox.h \
		/anaconda3/include/qt/QtWidgets/qdialog.h \
		/anaconda3/include/qt/QtWidgets/QApplication \
		/anaconda3/include/qt/QtWidgets/qapplication.h \
		/anaconda3/include/qt/QtWidgets/qdesktopwidget.h \
		/anaconda3/include/qt/QtWidgets/QPushButton \
		/anaconda3/include/qt/QtWidgets/qpushbutton.h \
		/anaconda3/include/qt/QtWidgets/qabstractbutton.h \
		/anaconda3/include/qt/QtCore/QCoreApplication
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_bgb.o: qrc_bgb.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_bgb.o qrc_bgb.cpp

qrc_bgo.o: qrc_bgo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_bgo.o qrc_bgo.cpp

qrc_bgx.o: qrc_bgx.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_bgx.o qrc_bgx.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

moc_clickableBt.o: moc_clickableBt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clickableBt.o moc_clickableBt.cpp

moc_gameplay.o: moc_gameplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gameplay.o moc_gameplay.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

